version: '3'
services:
  #服务名称
  mssql:
    #容器名称
    container_name: mssql
    #镜像名称    https://hub.docker.com/_/microsoft-mssql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    #    image: microsoft/mssql-server-linux:2017-latest
    #总是重启后启动
    restart: always
    #端口映射
    ports:
      - 1433:1433
    #挂载
    #    volumes:
    #      - ./data:/var/lib/rabbitmq
    #环境变量
    environment:
      - ACCEPT_EULA=Y
      #SA用户密码
      - SA_PASSWORD=asdfF@1234



  #  docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest
  #  docker run -d --name oracle \
  #  --privileged -v $(pwd)/oradata:/u01/app/oracle \
  #  -p 8080:8080 -p 1521:1521 absolutapps/oracle-12c-ee


#  oracle:
#    container_name: oracle
#    image: absolutapps/oracle-12c-ee
#    restart: always
#    privileged: true
#    ports:
#      - 8080:8080
#      - 1521:1521



#  mysql:
#    image: mysql:5.7
#    restart: always
#      ports:
#        - 8080:8080


