version: '3'
services:
  #服务名称
  node-exporter:
    image: prom/node-exporter
    #总是重启后启动
    restart: always
    #端口映射
    ports:
      - 9100:9100

  #服务名称
  prometheus:
    image: prom/prometheus
    #总是重启后启动
    restart: always
    volumes:
    - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
    #端口映射
    ports:
      - 9090:9090
  #服务名称
  grafana:
    image: grafana/grafana
    #总是重启后启动
    restart: always
    #端口映射
    ports:
      - 3000:3000

